// examples/vue/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue';
import { MarketplaceSDK } from '@mission_sciences/provider-sdk';

const APP_ID = 'YOUR_APP_ID';
const API_KEY = 'YOUR_API_KEY';

let sdk: MarketplaceSDK | null = null;

onMounted(() => {
  sdk = new MarketplaceSDK({
    applicationId:            APP_ID,
    apiKey:                   API_KEY,
    environment:              'production',   // 'demo' | 'production'
    autoStart:                true,
    themeMode:                'auto',          // 'light' | 'dark' | 'auto'
    warningThresholdSeconds:  300,            // seconds before expiry warning
    enableHeartbeat:          false,          // keep-alive ping
    heartbeatIntervalSeconds: 30,
    debug:                    false,
  });
  sdk.initialize().catch(console.error);
});

onUnmounted(() => { sdk?.destroy(); });
</script>

<template>
  <div>
    <!-- Your application content -->
  </div>
</template>

// examples/react/src/App.tsx
import { useEffect } from 'react';
import { MarketplaceSDK } from '@mission_sciences/provider-sdk';

const APP_ID = 'YOUR_APP_ID';
const API_KEY = 'YOUR_API_KEY';

export default function App() {
  useEffect(() => {
    const sdk = new MarketplaceSDK({
      applicationId:            APP_ID,
      apiKey:                   API_KEY,
      environment:              'production',   // 'demo' | 'production'
      autoStart:                true,
      themeMode:                'auto',          // 'light' | 'dark' | 'auto'
      warningThresholdSeconds:  300,            // seconds before expiry warning
      enableHeartbeat:          false,          // keep-alive ping
      heartbeatIntervalSeconds: 30,
      debug:                    false,
    });
    sdk.initialize().catch(console.error);
    return () => sdk.destroy();
  }, []);

  return (
    <div>
      {/* Your application content */}
    </div>
  );
}
